services:
  spring-service:
    build:
      context: ../spring-service
    image: local/spring-service:latest
    container_name: spring-service

  python-service:
    build:
      context: ../python-service
    image: local/python-service:latest
    container_name: python-service

  dotnet-service:
    build:
      context: ../dotnet-service
    image: local/dotnet-service:latest
    container_name: dotnet-service

  quarkus-native-service:
    build:
      context: ../quarkus-native-service
    image: local/quarkus-native-service:latest
    container_name: quarkus-native-service

  ngix-proxy:
    build:
      context: ../ngix-proxy
    image: local/ngix-proxy:latest
    container_name: ngix-proxy
    depends_on:
      - spring-service
      - python-service
      - quarkus-native-service
    ports:
      - "8080:8080"

  image-registry:
    build:
      context: ../image-registry
    image: local/image-registry:latest
    container_name: image-registry
    ports:
      - "5000:5000"
    volumes:
      - registry-data:/var/lib/registry

volumes:
  registry-data:
